### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by tutunci** [Breeze/temphire.angular2#5]
Hi,
I'm trying to build the project.
I've followed the Npm install steps but when gulp runs this error message is output

`[14:51:04] Finished 'client-install' after 12 s
[14:51:04] Starting 'client-build'...
[14:51:05] Using gulpfile ~/git/temphire.angular2/TempHire/gulpfile.js
[14:51:05] Starting 'build'...
Error: Error at /Users/maurizio/git/temphire.angular2/TempHire/app/main.ts:3:36: Cannot find module '../aot/app/app.module.ngfactory'.
    at check (/Users/maurizio/git/temphire.angular2/TempHire/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Tsc.typeCheck (/Users/maurizio/git/temphire.angular2/TempHire/node_modules/@angular/tsc-wrapped/src/tsc.js:86:9)
    at /Users/maurizio/git/temphire.angular2/TempHire/node_modules/@angular/tsc-wrapped/src/main.js:33:23
    at process._tickCallback (node.js:402:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:140:18)
    at node.js:1001:3
Compilation failed
[14:51:13] 'build' errored after 8.15 s
[14:51:13] Error: Command `node_modules/.bin/ngc -p tsconfig-aot.json` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:471:12)
[14:51:13] 'client-build' errored after 8.94 s
[14:51:13] Error: Command `gulp` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:471:12)`

Can you please help me on solving

Thanks,
Maurizio

**Comment by marcelgood** [comment]
@tutunci  Sorry about the delay. The issue was caused by TypeScript 2.1, which currently isn't compatible with Angular 2. I restricted TypeScript to 2.0.x in the package.json. Go ahead and get a fresh clone of the repo. It should build. Let me know how it goes.
